name: Update

on:
  workflow_call:

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Copy .env
        run: cp $GITHUB_WORKSPACE/.env.example $GITHUB_WORKSPACE/.env

      - name: Install/update dependencies
        run: composer install && composer update

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update
